################################################################################
# GLOBAL
################################################################################

################################################################################
# WEB Console
################################################################################
webConsole:
  replicaCount: 1
  image:
    repository: vitalykumov/hw-console
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  ports:
  - name: http
    containerPort: 8080
    protocol: TCP

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  lifecycle: {}

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    imagePullSecrets:
    name: ""

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  extraEnvs:
    - name: DEVICE_FOLDER
      value: "/var/console/devices/"
    - name: THEME
      value: dark

  podVolumeMounts:
  - name: webconsole-devices
    mountPath: /var/console/devices/devices.yaml

  volumes:
  - name: webconsole-devices
    configMap:
      name: devices
      items:
      - key: devices.yaml
        path: keys

  service:
    type: NodePort
    port: 8080
    name: webconsole

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx-alb"
    hosts:
      # Host is replaced with the value from terraform
      - host: webconsole.workflows.cat-dcloud.com
        paths:
          - path: /
    tls: []

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector:
    dedicated: process

  tolerations: []

  affinity: {}

################################################################################
# SSH SERVER
################################################################################
sshServer:
  enabled: true
  replicaCount: 1
  image:
    repository: vitalykumov/hw-console-sshserver
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  ports:
  - name: http
    containerPort: 2222
    protocol: TCP

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  lifecycle:

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    imagePullSecrets:
    name: ""

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  extraEnvs:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: TZ
      value: "Etc/UTC"
    - name: SUDO_ACCESS
      value: "false"
    - name: PASSWORD_ACCESS
      value: "true"
    - name: USER_PASSWORD
      value: "sshuser"
    - name: USER_NAME
      value: "sshuser"

  podVolumeMounts:
  volumes:
  service:
    type: NodePort
    port: 2222
    name: sshserver

  ingress:
    enabled: false
    annotations:
    hosts:
    tls: []

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector:
    dedicated: process

  tolerations: []

  affinity: {}