################################################################################
# GLOBAL
################################################################################

################################################################################
# WEB Console
################################################################################
webConsole:
  replicaCount: 1
  image:
    repository: mgarciasanes/webconsole
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  ports:
  - name: http
    containerPort: 8080
    protocol: TCP

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  lifecycle: {}

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    imagePullSecrets:
    name: ""

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  extraEnvs:
    - name: DEVICE_FOLDER
      value: "/var/console/devices/"
    - name: THEME
      value: dark

  podVolumeMounts:
  - name: webconsole-devices
    mountPath: /var/console/devices/devices.yaml

  volumes:
  - name: webconsole-devices
    configMap:
      name: devices
      items:
      - key: devices.yaml
        path: keys

  service:
    type: NodePort
    port: 8080
    name: webconsole

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx-alb"
      nginx.ingress.kubernetes.io/auth-keepalive: '10'
      nginx.ingress.kubernetes.io/auth-response-headers: authorization
      nginx.ingress.kubernetes.io/proxy-buffer-size: 1024k
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Forwarded-Server "$remote_addr";


    hosts:
      # Host is replaced with the value from terraform
      - host: webconsole.workflows.cat-dcloud.com
        paths:
          - path: /
    tls: []

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector:
    dedicated: process

  tolerations: []

  affinity: {}

################################################################################
# SSH SERVER
################################################################################
sshServer:
  enabled: true
  replicaCount: 1
  image:
    repository: mgarciasanes/sshserver
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  ports:
  - name: http
    containerPort: 2222
    protocol: TCP

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  lifecycle:

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    imagePullSecrets:
    name: ""

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  extraEnvs:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: TZ
      value: "Etc/UTC"
    - name: SUDO_ACCESS
      value: "false"
    - name: PASSWORD_ACCESS
      value: "true"
    - name: USER_PASSWORD
      value: "sshuser"
    - name: USER_NAME
      value: "sshuser"

  podVolumeMounts:
  - name: git-sync-code
    mountPath: /var/mountpoint/

  gcs:
    enabled: true
    replicaCount: 1
    image:
      repository: mgarciasanes/gcs
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: latest
    command:
    extraArgs:
    ports:
    imagePullSecrets: []
    securityContext:
      privileged: true

    extraEnvs:
      - name: HEALTHCHECK_FILE
        value: "/tmp/livenessprobe"
      - name: FORCE_DELETE
        value : "false"
      - name: ROOT_FOLDER
        value : "/var/mountpoint"
      - name: GIT_TOKEN
        valueFrom:
          secretKeyRef:
            key: GIT_TOKEN
            name: kitchen
      - name: LOOP_DELAY
        value : "20"

    reposToPull:
    - github: github.com/cisco-dcloud/argo-workflows-templates
      branch: main
      folderName: argo-workflows-templates

    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - find /tmp/ -mmin -5 | grep livenessprobe
      initialDelaySeconds: 60
      periodSeconds: 20
      
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - test -f /tmp/livenessprobe
      initialDelaySeconds: 60
      periodSeconds: 20

    podVolumeMounts:
    - name: git-sync-code
      mountPath: /var/mountpoint/

  volumes:
  - name: git-sync-code
    emptyDir: {}


  service:
    type: NodePort
    port: 2222
    name: sshserver

  ingress:
    enabled: false
    annotations:
    hosts:
    tls: []

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector:
    dedicated: process

  tolerations: []

  affinity: {}