apiVersion: v1
kind: ConfigMap
metadata:
  name: devices
data:
  devices.yaml:
    devices:
      - hideAddress: true
        host: sshserver
        name: SSHServer
        user: "sshuser"
        password: "sshuser"
        port: 22
        power:
          capabilities:
          - all
          id: '3368'
        type: switch