################################################################################
# WEB CONSOLE 
################################################################################
{{- if .Values.webConsole.ingress.enabled -}}
{{- $fullName := include "wc.webConsole.fullname" . -}}
{{- $svcName := .Values.webConsole.service.name -}}
{{- $svcPort := .Values.webConsole.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "wc.webConsole.labels" . | nindent 4 }}
  {{- with .Values.webConsole.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.webConsole.ingress.tls }}
  tls:
    {{- range .Values.webConsole.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.webConsole.ingress.hosts }}
    - host: {{ .host| quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $svcName }}
                port: 
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
