################################################################################
#  WEB CONSOLE / SSH SERVER 
################################################################################
{{- if .Values.webConsole.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wc.webConsole.serviceAccountName" . }}
  labels:
    {{- include "wc.webConsole.labels" . | nindent 4 }}
  {{- with .Values.webConsole.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.webConsole.serviceAccount.imagePullSecrets }}
imagePullSecrets: 
   {{- with .Values.webConsole.serviceAccount.imagePullSecrets }}{{ toYaml . | nindent 2 }}
   {{- end }}
{{- end }}
{{- end }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "wc.sshServer.serviceAccountName" . }}
rules:
  - apiGroups:
        - ""
    resources:
      - configmaps
    verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "wc.sshServer.serviceAccountName" . }}
subjects:
- namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
  name: {{ include "wc.sshServer.serviceAccountName" . }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "wc.sshServer.serviceAccountName" . }}

#
---
#

{{- if .Values.sshServer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wc.sshServer.serviceAccountName" . }}
  labels:
    {{- include "wc.sshServer.labels" . | nindent 4 }}
  {{- with .Values.sshServer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.sshServer.serviceAccount.imagePullSecrets }}
imagePullSecrets: 
   {{- with .Values.sshServer.serviceAccount.imagePullSecrets }}{{ toYaml . | nindent 2 }}
   {{- end }}
{{- end }}
{{- end }}