{{- if .Values.webConsole.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wc.webConsole.serviceAccountName" . }}
  labels:
    {{- include "wc.webConsole.labels" . | nindent 4 }}
  {{- with .Values.webConsole.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.webConsole.serviceAccount.imagePullSecrets }}
imagePullSecrets: 
   {{- with .Values.webConsole.serviceAccount.imagePullSecrets }}{{ toYaml . | nindent 2 }}
   {{- end }}
{{- end }}
{{- end }}

--- 

{{- if .Values.sshServer.serviceAccount.create -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wc.sshServer.serviceAccountName" . }}
  labels:
    {{- include "wc.sshServer.labels" . | nindent 4 }}
  {{- with .Values.sshServer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.sshServer.serviceAccount.imagePullSecrets }}
imagePullSecrets: 
   {{- with .Values.sshServer.serviceAccount.imagePullSecrets }}{{ toYaml . | nindent 2 }}
   {{- end }}
{{- end }}


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-ro
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs:     ["get", "list", "watch"]

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-admin
rules:
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflows/finalizers
      - workfloweventbindings
      - workfloweventbindings/finalizers
      - workflowtasksets
      - workflowtasksets/finalizers
      - workflowtemplates
      - workflowtemplates/finalizers
      - cronworkflows
      - cronworkflows/finalizers
      - clusterworkflowtemplates
      - clusterworkflowtemplates/finalizers

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflows
rules:
  - verbs:
      - get
      - watch
      - patch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - watch
    apiGroups:
      - ''
    resources:
      - pods/log
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/exec
  - verbs:
      - create
    apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
  - verbs:
      - list
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
      - workflowartifactgctasks
  - verbs:
      - patch
    apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets/status
      - workflowartifactgctasks/status
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}{{ include "wc.sshServer.serviceAccountName" . }}
subjects:
- namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
  name: {{ include "wc.sshServer.serviceAccountName" . }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-ro

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows
subjects:
- kind: ServiceAccount
  name: {{ include "wc.sshServer.serviceAccountName" . }} 
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: argo-workflows
  apiGroup: rbac.authorization.k8s.io
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-admin
subjects:
- kind: ServiceAccount
  name: {{ include "wc.sshServer.serviceAccountName" . }} 
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: argo-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wc.sshServer.serviceAccountName" . }} 
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "wc.sshServer.serviceAccountName" . }} 
type: kubernetes.io/service-account-token


{{- end }}